### ISSUE TITLE
Can't run pyfontfixer on Ubuntu 14.04

### ISSUE THREAD

**Issue by aagontuk** [sarim/pyfontfixer#3]
First I downloaded and installed pyfontfixer-0.2.deb from Google Code Archive. If I try to run it, it gives following errors:

```
Traceback (most recent call last):
  File "/usr/share/pyfontfixer/pyfontfixer.py", line 25, in <module>
    from BeautifulSoup import BeautifulStoneSoup as BTS , Tag
ImportError: Bad magic number in /usr/share/pyfontfixer/BeautifulSoup.pyc
```

Then I cloned your repository and tried to run the `pyfontfixer.py` and it gives similar error with slight difference. Its giving following error:

```
Traceback (most recent call last):
  File "/usr/share/pyfontfixer/pyfontfixer.py", line 25, in <module>
    from BeautifulSoup import BeautifulStoneSoup as BTS , Tag
ImportError: Bad magic number in /usr/share/pyfontfixer/BeautifulSoup.pyc
```

**Comment by AnwarShah** [comment]
I got this same error on newly installed Kubuntu 16.04. Although I ran it successfully in my older 16.04 installation!
